apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-demo
  template:
    metadata:
      labels:
        app: secret-demo
    spec:
      volumes:
      - name: secrets
        secret:
          secretName: db-secret

      containers:
      - name: app
        image: busybox
        command: ["sh", "-c", "cat /secrets/password && sleep 3600"]
        volumeMounts:
        - name: secrets
          mountPath: /secrets
          readOnly: true
